### ISSUE TITLE
Signup confirm button

### ISSUE THREAD

**Issue by modula2019** [SA-Places-API/support#2]
Hi,
When one clicks the Confirm button below, it launches a localhost url like below. As a result, the confirmation is not successful.

http://localhost:4200/verify-email

<img width="235" alt="image" src="https://user-images.githubusercontent.com/54540093/201348439-c53692bf-3e06-458c-bf67-068310936e2e.png">

Thanks

**Comment by Teebo** [comment]
Hi @modula2019 , thank you for your query.
Please try confirming your email again. It should work now.
